# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(281C1C)
$foreground = rgb(DBD4D4)
$color0 = rgb(504242)
$color1 = rgb(33050C)
$color2 = rgb(33070E)
$color3 = rgb(2B2525)
$color4 = rgb(2B2625)
$color5 = rgb(901213)
$color6 = rgb(726463)
$color7 = rgb(C3BAB9)
$color8 = rgb(888282)
$color9 = rgb(450610)
$color10 = rgb(770000)
$color11 = rgb(393231)
$color12 = rgb(ff0000)
$color13 = rgb(C0181A)
$color14 = rgb(988584)
$color15 = rgb(C3BAB9)
